# Generated by Django 3.1.4 on 2020-12-17 11:41

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180821_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(null=True, upload_to=shop.models.get_upload_path),
        ),
    ]
