# Generated by Django 3.1.5 on 2021-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210222_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
