# Generated by Django 3.1.5 on 2021-01-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tel_number',
        ),
    ]
