# Generated by Django 3.1.5 on 2021-02-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_tel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, verbose_name='Номер телефона'),
        ),
    ]
